[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_ct = "C22JEQiqjh1QTPFkZuiubgYtFkdH58dqZr5rWzqk4kYz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/absar/my_new_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"